baseURL: 'http://articles.potee.ru/'
languageCode: 'en-us'
title: Piece of Script
theme: cactus
googleAnalytics: "G-SS325GBRP9"
menu:
  main:
  - name: "Home"
    url: /
    weight: 1
  - name: "All Articles"
    url: "/articles"
    weight: 2
  - name: "Categories"
    url: "/categories"
    weight: 3
  - name: "Tags"
    url: "/tags"
    weight: 4
  - name: "About"
    url: "/about"
    weight: 5

params:
  logo: images/logo.png
  description: "Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. Unlike systems that dynamically build a page with each visitor request, Hugo builds pages when you create or update your content. Since websites are viewed far more often than they are edited, Hugo is designed to provide an optimal viewing experience for your website’s end users and an ideal writing experience for website authors."
  mainSectionTitle: "Articles"
  mainSection: "articles"
  showAllPostsOnHomePage: false
  postsOnHomePage: 5
  tagsOverview: true
  tocInline: true
  colortheme: "dark"
  social:
    - name: telegram
      link: https://t.me/pieceofscript

markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: "dracula"
    tabWidth: 4