baseURL: 'https://blog.potee.ru/'
languageCode: 'ru'
title: Piece of Code
theme: cactus
googleAnalytics: "G-SS325GBRP9"
DefaultContentLanguage: ru
languages:
  ru:
    languageName: Russian
    weight: 1
    contentDir: content/ru
    menu:
      main:
      - name: "Главная"
        url: /
        weight: 1
      - name: "Все Статьи"
        url: "/posts/"
        weight: 2
      - name: "Категории"
        url: "/categories/"
        weight: 3
      - name: "Тэги"
        url: "/tags/"
        weight: 4
      - name: "О Проекте"
        url: "/about/"
        weight: 5

    params:
      description: |
        >«Бороться и искать, найти и не сдаваться... » - В.А. Каверин

        Здесь ты сможешь найти полезные материалы по программированию, администрированию, безопасности и много чего ещё.

        Результаты бессонные ночей энтузиастов, в погоне за истинной, специально для тебя, дорогой читатель.

      mainSectionTitle: "Статьи"
      mainSection: "articles"
      showAllPostsOnHomePage: false
      postsOnHomePage: 5
      tagsOverview: true
      tocInline: true
      colortheme: "dark"
      social:
        - name: telegram
          link: https://t.me/pieceofscript

markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: "dracula"
    tabWidth: 4